### PR TITLE
Added powerflow sensor

### PR DESCRIPTION
**Pull request by Ads5555**
Added powerflow as a new sensor, if it is present. Kept it to the basics for this first PR.

Fixes: https://github.com/TimSoethout/goodwe-sems-home-assistant/issues/52

image

### CODE REVIEW

**Comment by TimSoethout** [comment]
I think it looks great!
I can't test it myself, but if you say it works I can release it as a beta release. :)

**Comment by Ads5555** [comment]
Thanks, what ever you are happy with.

Those values pictured are coming from the new sensor in the HA dev tools so brings it all in.

**Comment by darek-margas** [comment]
Works for me. However, I think these two "charts" I mentioned are needed too. One has daily balance and one total balance which could be used as-is for energy page. With this code change is just two to add in sensor.

**Comment by rmartinsgr** [comment]
I would love to test this because i have a homekit but i don't know how to install a beta version...
I have it installed from Hacs...
Anyone can tell me how to test? Just replace the files in the custome_components folder ?

Ty

**Comment by Ads5555** [comment]
> 
> 
> I would love to test this because i have a homekit but i don't know how to install a beta version... I have it installed from Hacs... Anyone can tell me how to test? Just replace the files in the custome_components folder ?
> 
> Ty

Go to Hacs -> Integrations -> GoodWe SEMS API -> Reinstall -> Select Beta.

**Comment by rmartinsgr** [comment]
> Go to Hacs -> Integrations -> GoodWe SEMS API -> Reinstall -> Select Beta.

Thanks. Seems to Work just fine. Thanks :)

**Comment by darek-margas** [comment]
> 
> 
> > Works for me. However, I think these two "charts" I mentioned are needed too. One has daily balance and one total balance which could be used as-is for energy page. With this code change is just two to add in sensor.
> 
> Could definitely look at adding those now I have a better idea. But i personally just added new sensors to configuration.yaml for to get that info. `energy_load` then shows up as a sensor you can add to the energy dashboard components. Might take a while for the data to flow in.
> ### House consumption

I can add these here, just recently spent some time fiddling with localtuya and gateway support. 
Maybe some time next week. Daily worked perfectly for me but total had 1h rollback every midnight. May work for others in different TZ.

**Pull request merged**
